asr_model: faster_whisper
auto_send:
  enabled: false
  delay_ms: 2000
web_speech_api:
  language: zh-CN
  continuous: true
  interim_results: true
  max_alternatives: 1
faster_whisper:
  language: zh
  model_path: distil-large-v3
  download_root: models/whisper
  device: auto
  compute_type: int8
whisper_cpp:
  model_name: small
  print_realtime: false
  print_progress: false
  language: auto
  model_dir: models/whisper
  prompt: ''
whisper:
  name: medium
  download_root: models/whisper
  device: cpu
  prompt: ''
openai_whisper:
  model: whisper-1
  language: ''
  api_key: ${OPENAI_API_KEY}
  base_url: ''
  prompt: ''
